WIP Migrate my site to Vite (#17)
* nextjs with mdx init

* enable static export

* add content to navigation

* Move to vite

* fix cloudflare Error: Cannot find module

* update deets

* Add avatar